# Generated by Django 5.0.6 on 2024-05-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='오늘의 사진'),
        ),
    ]
