# Generated by Django 5.0.5 on 2024-05-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='프로필사진')),
                ('username', models.TextField(verbose_name='유저 아이디')),
                ('joined_at', models.DateTimeField(verbose_name='가입 날짜')),
                ('post_num', models.IntegerField(verbose_name='게시물 개수')),
            ],
        ),
    ]
