# Generated by Django 5.0.6 on 2024-05-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('detail', models.TextField(max_length=300)),
            ],
        ),
    ]
