# Generated by Django 5.0.6 on 2024-05-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary', models.TextField(verbose_name='오늘의 일기')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='오늘의 사진')),
            ],
        ),
        migrations.AlterField(
            model_name='todolist',
            name='detail',
            field=models.TextField(max_length=300, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo',
            field=models.TextField(max_length=100, verbose_name='todo'),
        ),
    ]
